[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neocomplete'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'jacoborus/tender.vim'


[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'tpope/vim-obsession'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'itchyny/vim-haskell-indent'

[[plugins]]
repo = 'kovisoft/slimv'

[[plugins]]
repo = 'tpope/vim-markdown'

[[plugins]]
repo = 'rust-lang/rust.vim'
